version: "3"

services:
  # FastAPI server for demo services
  image-api:
    container_name: edutap-image-api-fastapi-backend
    image: ghcr.io/edutap-eu/edutap.image_api:latest
    build:
      context: .
      args:
        - API_HTTP_PORT=${API_HTTP_PORT:-80}
    dns:
      ${DNS:-8.8.8.8}
    ports:
      - "${HTTP_PORT:-9085}:${API_HTTP_PORT:-80}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.image-api.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.image-api.entrypoints=https,http"
      # - "traefik.http.routers.image-api.tls.certresolver=le"

  traefik:
    image: "traefik:latest"
    container_name: "edutap-image-api-traefik"
    dns:
      ${DNS:-8.8.8.8}

    depends_on:
      - image-api

    command:
      - "--providers.file.filename=/traefik.yaml"
      - "--log.level=DEBUG"

    ports:
      - "80:80"
      - "${HTTPS_PORT:-8443}:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt/${DOMAIN}:/letsencrypt"
      - "./traefik.yaml:/traefik.yaml"
